org.objectweb.asm_3.3.1.v201101071600.jar=/usr/share/java/objectweb-asm/asm-all.jar:/usr/share/java/asm3-all.jar
# Try to link source bundle to the one build by P2. If it does not work, then fall back on icu4j, 
# which is not actually a source bundle, but will exists, and will allow for the build to happen.
com.ibm.icu.source_4.4.2.v20110823.jar=/usr/share/java/icu4j-eclipse/plugins/com.ibm.icu.source_4.4.2.v20110823.jar:/usr/share/java/com.ibm.icu.source-4.4.jar:/usr/share/java/com.ibm.icu.source-4.4.jar:/usr/share/java/icu4j.jar

javax.inject_1.0.0.v20091030.jar=/usr/share/java/atinject.jar
javax.annotation_1.0.0.v20101115-0725.jar=/usr/share/java/geronimo-annotation.jar
org.apache.batik.bridge_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-bridge.jar
org.apache.batik.css_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-css.jar
org.apache.batik.dom_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-dom.jar
org.apache.batik.dom.svg_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-svg-dom.jar
org.apache.batik.ext.awt_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-awt-util.jar
org.apache.batik.parser_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-parser.jar
org.apache.batik.pdf_1.6.0.v201105071520.jar=/usr/share/java/fop.jar
org.apache.batik.svggen_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-svggen.jar
org.apache.batik.swing_1.6.0.jar=/usr/share/java/batik/batik-swing.jar
org.apache.batik.transcoder_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-transcoder.jar
org.apache.batik.util_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-util.jar
org.apache.batik.util.gui_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-gui-util.jar
org.apache.batik.xml_1.6.0.v201011041432.jar=/usr/share/java/batik/batik-xml.jar
org.w3c.css.sac_1.3.1.v200903091627.jar=/usr/share/java/sac.jar
#org.w3c.dom.smil_1.0.1.v200903091627.jar=/usr/share/java/xml-commons-apis.jar
javax.xml_1.0.1.v200903091627.jar=/usr/share/java/xml-commons-apis.jar
org.w3c.dom.svg_1.1.0.v201011041433.jar=/usr/share/java/xml-commons-apis-ext.jar
